# Generated by Django 3.2.7 on 2021-09-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonPage_Querry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customername', models.CharField(default='', max_length=50)),
                ('phone_no', models.BigIntegerField(default='')),
                ('email_id', models.EmailField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('customer_DOB', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('pincode', models.BigIntegerField(default='')),
                ('mobileno', models.BigIntegerField(default='')),
                ('email', models.EmailField(default='', max_length=50)),
                ('adharno', models.BigIntegerField(default='')),
                ('product_type', models.CharField(default='', max_length=50)),
                ('customer_username', models.CharField(default='', max_length=50)),
                ('customer_password', models.CharField(default='', max_length=50)),
                ('customer_photo', models.ImageField(default=None, upload_to='images/')),
                ('customer_idfile', models.ImageField(default=None, upload_to='files/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBillpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default='')),
                ('postpaid_customerMob', models.CharField(default='', max_length=100)),
                ('mins_callduration', models.BigIntegerField(default='')),
                ('call_type', models.CharField(default='', max_length=100)),
                ('ExistingPackRate', models.BigIntegerField(default='')),
                ('extraCallRPM', models.BigIntegerField(default='')),
                ('extraData', models.CharField(default='', max_length=100)),
                ('TotalMsgRate', models.CharField(default='', max_length=100)),
                ('TotalBill', models.BigIntegerField(default='')),
                ('Bill_issued', models.CharField(default='', max_length=100)),
                ('Bill_due', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(default='', max_length=10)),
                ('mobileno', models.CharField(default='', max_length=15)),
                ('type', models.CharField(default='', max_length=15)),
                ('Message', models.CharField(default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default='')),
                ('customerMob', models.CharField(default='', max_length=100)),
                ('Data_usage', models.CharField(default='', max_length=100)),
                ('Message_Usage', models.CharField(default='', max_length=100)),
                ('DataAndMsg_RefillTime', models.CharField(default='', max_length=100)),
                ('CallBalance', models.CharField(default='', max_length=100)),
                ('Validity', models.DateField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DongleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('mob_no', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=10)),
                ('payment_method', models.CharField(default='Cash On Delivery', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonglePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('dongle_modelname', models.CharField(default='', max_length=50)),
                ('dongle_modelpic', models.ImageField(default='', upload_to='DongleImg/')),
                ('dongle_InternetSpeed', models.CharField(default='', max_length=50)),
                ('dongle_RouterSpeed', models.CharField(default='', max_length=50)),
                ('dongle_description', models.CharField(default='', max_length=100)),
                ('dongle_price', models.BigIntegerField(default='')),
                ('dongle_quanity', models.BigIntegerField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('empcode', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('name', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('address', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('emailid', models.EmailField(blank=True, default='NO NAME', max_length=50)),
                ('phonenumber', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('gender', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('pincode', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('aadhaarno', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('empphoto', models.ImageField(blank=True, default='NO NAME', upload_to='Empimages/')),
                ('empidfile', models.FileField(blank=True, default='NO NAME', upload_to='Empfiles/')),
                ('dateofjoining', models.DateField(blank=True, default='NO NAME')),
                ('dateofbirth', models.DateField(default='NO NAME')),
                ('salary', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('username', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('password', models.CharField(blank=True, default='NO NAME', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.BigIntegerField()),
                ('email', models.EmailField(default='', max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPostpaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('postplan_id', models.IntegerField(default='')),
                ('postplan_name', models.CharField(default='', max_length=50)),
                ('postdescription', models.CharField(default='', max_length=500)),
                ('monthly_rent', models.CharField(default='', max_length=100)),
                ('postplan_type', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPrepaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('plan_id', models.IntegerField(default='')),
                ('preplan_name', models.CharField(default='', max_length=50)),
                ('pre_description', models.CharField(default='', max_length=500)),
                ('pre_validity', models.CharField(default='', max_length=100)),
                ('preplan_type', models.CharField(default='', max_length=100)),
                ('pre_amount', models.IntegerField(default='')),
                ('data', models.DecimalField(decimal_places=2, default='', max_digits=9)),
                ('msg', models.IntegerField(default='')),
                ('voice', models.DecimalField(decimal_places=2, default='', max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fetchid', models.IntegerField(default='')),
                ('mobileno', models.BigIntegerField(default='')),
                ('product_type', models.CharField(default='', max_length=50)),
                ('preplan_name', models.CharField(default='', max_length=50)),
                ('pre_description', models.CharField(default='', max_length=500)),
                ('pre_validity', models.CharField(default='', max_length=100)),
                ('preplan_type', models.CharField(default='', max_length=100)),
                ('pre_amount', models.IntegerField(default='')),
                ('data', models.DecimalField(decimal_places=2, default='', max_digits=9)),
                ('msg', models.IntegerField(default='')),
                ('voice', models.DecimalField(decimal_places=2, default='', max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
